#!/usr/bin/env bash

cd "${HOME}"

# Link in files, replacing whatever's already there.
ln -fs "${HOME}/Code/dotfiles/git/gitconfig"     "${HOME}/.gitconfig"
ln -fs "${HOME}/Code/dotfiles/git/gitignore_global"     "${HOME}/.gitignore_global"
ln -fs "${HOME}/Code/dotfiles/vim/vimrc"         "${HOME}/.vimrc"
ln -fs "${HOME}/Code/dotfiles/bash/bashrc"         "${HOME}/.bashrc"
ln -fs "${HOME}/Code/dotfiles/bash/inputrc"         "${HOME}/.inputrc"
ln -fs "${HOME}/Code/dotfiles/tmux/tmuxconf"         "${HOME}/.tmux.conf"

mkdir -p "${HOME}/.vim/bundle"
git clone git@github.com:gmarik/vundle.git "${HOME}/.vim/bundle/vundle"

vim +BundleInstall +qall
