#!/usr/bin/env bash

cd "${HOME}"

# Link in files, replacing whatever's already there.
ln -fs "${HOME}/dotfiles/git/gitconfig"     "${HOME}/.gitconfig"
ln -fs "${HOME}/dotfiles/git/gitignore_global"     "${HOME}/.gitignore_global"
ln -fs "${HOME}/dotfiles/vim/vimrc"         "${HOME}/.vimrc"

mkdir -p "${HOME}/.vim/bundle"
git clone git@github.com:gmarik/vundle.git "${HOME}/.vim/bundle/vundle"

vim +BundleInstall +qall
