"Turns on syntax highlighting"
syntax on

"Basic settings"
set nocompatible "Fixes old Vi bugs"
set backspace=indent,eol,start "Makes backspace work"
set history=500 "Sets undo history size"
set ruler "Sets up status bar"
set number "Turns on line numbering"
set tabstop=4 "Sets indent size of tabs"
set softtabstop=4 "Soft tabs"
set expandtab "Tabs suck. Spaces rule."
set shiftwidth=4 "Sets auto-indent size"
set laststatus=2 "Always keeps the status bar active"
set autoindent "Turns on auto-indenting"
set smartindent "Remembers previous indent when creating new lines"
set cursorline
set cursorcolumn
set t_Co=256 "Sets terminal to use 256 colors"


"Search settings"
set hlsearch "Highlights search terms"
set showmatch "Highlights matching parentheses"
set ignorecase "Ignores case when searching"
set smartcase "Unless you put some caps in your search term"


"Key mappings"
inoremap jj <Esc>`^
set pastetoggle=<F2>


"Window movement mappings"
nnoremap <c-h> <c-w>h
nnoremap <c-l> <c-w>l
nnoremap <c-j> <c-w>j
nnoremap <c-k> <c-w>k

au FileType make setlocal noexpandtab

"Gets rid of trailing whitespace"
autocmd BufWritePre * :%s/\s\+$//e

"Vundle stuff"
"
filetype off                   " required!

" Setting up Vundle - the vim plugin bundler
    let iCanHazVundle=1
    let vundle_readme=expand('~/.vim/bundle/vundle/README.md')
    if !filereadable(vundle_readme)
        echo "Installing Vundle.."
        echo ""
        silent !mkdir -p ~/.vim/bundle
        silent !git clone https://github.com/gmarik/vundle ~/.vim/bundle/vundle
        let iCanHazVundle=0
    endif
    set rtp+=~/.vim/bundle/vundle/
    call vundle#rc()
    Bundle 'gmarik/vundle'
    "Add bundles here
    " Awesome syntax highlighting
    Bundle 'Syntastic'
    " Cool colorscheme
    Bundle 'altercation/vim-colors-solarized'
    " Gnarly git stuff
    Bundle 'https://github.com/tpope/vim-fugitive'
    " coffee script plugin
    Bundle 'kchmck/vim-coffee-script'
    " Better file browser
    Bundle 'scrooloose/nerdtree'
    " Automatically sort python imports
    Bundle 'fisadev/vim-isort'
    " XML/HTML tags navigation
    Bundle 'matchit.zip'
    " Kick ass autocompletion
    " See https://news.ycombinator.com/item?id=5169062 for more instructions
    " if necessary
    Bundle 'Valloric/YouCompleteMe'
    " Yank history navigation
    Bundle 'YankRing.vim'

    "...All other bundles...
    if iCanHazVundle == 0
        echo "Installing Bundles, please ignore key map error messages"
        echo ""
        :BundleInstall
    endif
" Setting up Vundle - the vim plugin bundler end

"Filetype settings"
filetype plugin indent on "Turns on plugin/indentation support for specific filetypes"

" Set colorscheme
set background=dark
let g:solarized_termcolors=256
colorscheme solarized

"Allow crosshair cursor highlighting."
hi CursorLine   cterm=NONE ctermbg=235
hi CursorColumn cterm=NONE ctermbg=235
nnoremap <Leader>c :set cursorline! cursorcolumn!<CR>
